### ISSUE TITLE
Alerting naar 1 kanaal (slack?), niet meer naar Teams

### ISSUE THREAD

**Issue by joostvanderborg** [GemeenteNijmegen/aws-monitoring#34]

**Comment by BramWithaar** [comment]
Indien Slack dan moeten er ook licenties komen.
We moeten minstens 12 maanden terug binnenkomen alerts + opvolging terug kunnen halen ivm de DigiD audit.
Slack gaat naar 90 dagen terug in de gratis versie.

Betaalde versie kost 6,25 euro per user per maand.
https://app.slack.com/plans/T8SU32KRT
Vereist lig uitzoeken voor hoeveel users we dan een betaalde licentie nodig hebben.

Qua compliancy en meeliften op wat er is ligt het meer voor de hand om Teams te gaan gebruiken

**Comment by joostvanderborg** [comment]
Woensdag even bespreken?

**Comment by joostvanderborg** [comment]
Voorstel: Bram zoekt uit of we (API)toegang tot Topdesk kunnen krijgen. Als dat kan: Initieel laten we meldingen dan binnenkomen in Slack, waar we een 'maak topdesk-ticket'-knop aan het bericht toevoegen. We werken ondertussen aan betere monitoring (minder ruis).

**Comment by joostvanderborg** [comment]
Zie [#113](https://github.com/GemeenteNijmegen/devops/issues/113) voor issue topdesk-toegang. Epic in https://github.com/GemeenteNijmegen/devops/issues/23
